// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

type Post struct {
	ID        int32
	Title     string
	Published bool
	AuthorId  int32
}

type User struct {
	ID   int32
	Name string
}
