// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgres

import (
	"database/sql"
	"time"
)

type Post struct {
	ID        string
	Title     string
	Published bool
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
	AuthorID  string
}

type User struct {
	ID        string
	Name      string
	CreatedAt time.Time
	UpdatedAt time.Time
	DeletedAt sql.NullTime
}
